# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pull Request check version changes

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Latest Release
      uses: pozetroninc/github-action-get-latest-release@v0.5.0
      id: oldrls
      with:
        repository: ekazukii/discord_stat_bot
    - name: Read package.json
      uses: tyankatsu0105/read-package-version-actions@v1
      id: package-version
    - name: Add v in from of package.json version
      id: package-version-with-v
      run: echo ::set-output name=version::v${{ steps.package-version.outputs.version }}
    - name: Show versions
      run: echo "${{ steps.oldrls.outputs.release }} == ${{ steps.package-version-with-v.outputs.version }}"
    - name: Fail if version didn't changed
      run: exit 1
      if: steps.oldrls.outputs.release == "steps.package-version.outputs.version