name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build environment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@ekazukii'
    - run: npm install
    - run: npm publish
      name: Publish package
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Read package.json
      uses: tyankatsu0105/read-package-version-actions@v1
      id: package-version
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.package-version.outputs.version }}
        release_name: Version ${{ steps.package-version.outputs.version }}
    - name: 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd ./Ekasite
          npm update
          cd ./src
          pm2 restart index.js

  