# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pull Request tests

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> $GITHUB_WORKSPACE/.env
    - run: echo "XBOX_API_KEY=${{ secrets.XBOX_API_KEY }}" >> $GITHUB_WORKSPACE/.env
    - run: echo "RIOT_API=${{ secrets.RIOT_API }}" >> $GITHUB_WORKSPACE/.env
    - run: ls -A
    - run: npm ci
    - run: npm run build --if-present
    - run: chmod -R u+x node_modules/nyc/bin
    - run: sudo npm run coverage
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: coverage/lcov.info