# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pull Request tests

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        XBOX_API_KEY: ${{ secrets.XBOX_API_KEY }}
        USERNAME: ${{ secrets.USERNAME }}
    - run: npm coverage
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          XBOX_API_KEY: ${{ secrets.XBOX_API_KEY }}
          USERNAME: ${{ secrets.USERNAME }}
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: coverage/lcov.info